- hosts: all
  tasks:
  - name: aaa 
    community.windows.win_domain_user:
      name: bob
      firstname: Bob
      surname: Smith
      password: B0bP4ssw0rd
      state: present
      domain_username: LAB\administrator
      domain_password: P@sssw0rd
      domain_server: dc01.lab.loc
