- hosts: all
  tasks:
  - name: Create AD User 
    community.windows.win_domain_user:
      name: "{{ UserList.list.1.name }}"
      firstname: "{{ UserList.list.1.firstname }}"
      surname: "{{ UserList.list.1.surename }}"
      password: B0bP4ssw0rd
      state: present
