- hosts: all
  tasks:
  - name: Create AD User 
    community.windows.win_domain_user:
      name: "{{ UserList.list.0.name }}"
      firstname: "{{ UserList.list.0.firstname }}"
      surname: "{{ UserList.list.0.surename }}"
      password: B0bP4ssw0rd
      state: present
