- hosts: all
  tasks:
  - name: Create AD User 
    community.windows.win_domain_user:
      name: "{{ item.list.name }}"
      firstname: "{{ item.list.firstname }}"
      surname: "{{ item.list.surename }}"
      password: B0bP4ssw0rd
      state: present
    with_items: "{{ UserList }}"
