- hosts: all
  tasks:
  - name: Create AD User 
    community.windows.win_domain_user:
      name: "{{ item.name }}"
      firstname: "{{ item.firstname }}"
      surname: "{{ item.surename }}"
      password: B0bP4ssw0rd
      state: present
    with_items: "{{ UserList.list }}"
