- hosts: localhost
  tasks:
  - name: Read users from CSV file
    read_csv:
      path: '/tmp/users.csv'
      fieldnames: name,firstname,surename
      delimiter: ';'
    register: users
    delegate_to: localhost

  - debug:
      msg: 'User {{ users.dict.owen.name }} has UID {{ users.dict.owen.firstname }} and GID {{ users.dict.owen.surename }}'
