- hosts: localhost
  tasks:
  - name: Read users from CSV file
    read_csv:
      path: '/tmp/users.csv'
      fieldnames: name,firstname,surename
      delimiter: ','
    register: users
    delegate_to: localhost
