- hosts: localhost
  connection: local
  tasks:
  - name: Read users from CSV file
    read_csv:
      path: users.csv
      fieldnames: name,firstname,surename
      delimiter: ';'
    register: users

  - debug:
      msg: 'User {{ users.dict.dag.name }} has UID {{ users.dict.dag.firstname }} and GID {{ users.dict.dag.surename }}'
