- hosts: all
  tasks:
  - name: Read users from CSV file
    read_csv:
      path: /tmp/users.csv
      fieldnames: name,firstname,surename
      delimiter: ','
    register: users
    delegate_to: localhost
    
  - debug:
      var: ansible_search_path
      
  - name: Artifact Public IP to Tower Workflows
    set_stats:
      data:
        UserList: "{{ users }}"
